[package]
name = "bevy_draw_debug"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.7", default-features = false, features = ["render"] }
once_cell = "1.12"

[dev-dependencies]
bevy = "0.7"
bevy_flycam = "0.7"

[[example]]
name = "basic"
path = "examples/basic.rs"
